### ISSUE TITLE
0.9.0 throws java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by avackova** [tepi/FilteringTable#26]
After updating FilteringTable plugin to 0.9.0 version following exception is thrown:

```
java.lang.NoSuchMethodError: com.vaadin.ui.Component.setParent(Lcom/vaadin/ui/HasComponents;)V
    at org.vaadin.hene.popupbutton.PopupButton.setContent(PopupButton.java:129)
    at org.tepi.filtertable.datefilter.DateFilterPopup.buildPopup(DateFilterPopup.java:116)
    at org.tepi.filtertable.datefilter.DateFilterPopup.initContent(DateFilterPopup.java:247)
    at com.vaadin.ui.CustomField.getContent(CustomField.java:92)
    at org.tepi.filtertable.datefilter.DateFilterPopup.<init>(DateFilterPopup.java:56)
    at org.tepi.filtertable.FilterFieldGenerator.createDateField(FilterFieldGenerator.java:419)
    at org.tepi.filtertable.FilterFieldGenerator.createField(FilterFieldGenerator.java:298)
    at org.tepi.filtertable.FilterFieldGenerator.initializeFilterFields(FilterFieldGenerator.java:102)
    at org.tepi.filtertable.FilterTable.resetFilters(FilterTable.java:136)
    at org.tepi.filtertable.FilterTable.setContainerDataSource(FilterTable.java:120)
    at cz.pse.vaadinutils.VaadinutilsUI.createAndConfigureFilterTable(VaadinutilsUI.java:198)
    at cz.pse.vaadinutils.VaadinutilsUI.createFilterTableComponent(VaadinutilsUI.java:104)
    at cz.pse.vaadinutils.VaadinutilsUI.init(VaadinutilsUI.java:94)
    at com.vaadin.ui.UI.doInit(UI.java:529)
    at com.vaadin.server.AbstractCommunicationManager.getBrowserDetailsUI(AbstractCommunicationManager.java:2468)
    at com.vaadin.server.AbstractCommunicationManager.handleBrowserDetailsRequest(AbstractCommunicationManager.java:2362)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:325)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:201)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:662)
15.7.2013 9:30:45 org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet Vaadinutils Application threw exception
java.lang.NoSuchMethodError: com.vaadin.ui.Component.setParent(Lcom/vaadin/ui/HasComponents;)V
    at org.vaadin.hene.popupbutton.PopupButton.setContent(PopupButton.java:129)
    at org.tepi.filtertable.datefilter.DateFilterPopup.buildPopup(DateFilterPopup.java:116)
    at org.tepi.filtertable.datefilter.DateFilterPopup.initContent(DateFilterPopup.java:247)
    at com.vaadin.ui.CustomField.getContent(CustomField.java:92)
    at org.tepi.filtertable.datefilter.DateFilterPopup.<init>(DateFilterPopup.java:56)
    at org.tepi.filtertable.FilterFieldGenerator.createDateField(FilterFieldGenerator.java:419)
    at org.tepi.filtertable.FilterFieldGenerator.createField(FilterFieldGenerator.java:298)
    at org.tepi.filtertable.FilterFieldGenerator.initializeFilterFields(FilterFieldGenerator.java:102)
    at org.tepi.filtertable.FilterTable.resetFilters(FilterTable.java:136)
    at org.tepi.filtertable.FilterTable.setContainerDataSource(FilterTable.java:120)
    at cz.pse.vaadinutils.VaadinutilsUI.createAndConfigureFilterTable(VaadinutilsUI.java:198)
    at cz.pse.vaadinutils.VaadinutilsUI.createFilterTableComponent(VaadinutilsUI.java:104)
    at cz.pse.vaadinutils.VaadinutilsUI.init(VaadinutilsUI.java:94)
    at com.vaadin.ui.UI.doInit(UI.java:529)
    at com.vaadin.server.AbstractCommunicationManager.getBrowserDetailsUI(AbstractCommunicationManager.java:2468)
    at com.vaadin.server.AbstractCommunicationManager.handleBrowserDetailsRequest(AbstractCommunicationManager.java:2362)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:325)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:201)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:662)
```
